apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ template "<CHARTNAME>.fullname" . }}
  labels:
    app: {{ template "<CHARTNAME>.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - {{ include "<CHARTNAME>.fullname" . | cat "md-" | nospace | trunc 24 }}
  componentKinds:
  - group: pods
    kind: Pods
  - group: ss
    kind: StatefulSet
  - group: service
    kind: Service
  - group: deployment
    kind: Deployment
  - group: rs
    kind: ReplicaSet
