# Default values for <CHARTNAME>.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

targetCluster:
  labelSelector:
    matchLabels:
      vendor: ICP
  resourceSelector:
    type: cpu
  compliances: ""

deployable:
  namespace: default
  helm:
    chartURL: https://github.com/IBM/charts/blob/master/repo/stable/ibm-nginx-dev-1.0.1.tgz?raw=true
    valuesURL: ""